### PR TITLE
Update employee_attrition.R

### PR DESCRIPTION
**Pull request by Nawin151**
Please approve my modification on Q1. Analysis 5

### CODE REVIEW

**Comment by Ricky0625** [comment]
Hello Nawin. Could you please clarify more on the issue and why it's necessary for me to approve your modification? Thanks!

**Comment by Nawin151** [comment]
Because before Analysis 5, if we execute Analysis 3 and 4, then it shows
error. After executing Analysis 5, then if we execute 3 and 4, then it
provides output.

**Comment by Nawin151** [comment]
Because before Analysis 5, if we execute Analysis 3 and 4, then it shows error. After executing Analysis 5, then if we execute 3 and 4, then it provides output. 
Thanks

**Comment by Ricky0625** [comment]
I see. I don't think I encountered this issue when I was doing this assignment two years ago. Ok, then, I will merge your changes into mine.

By the way, I can see that you're an APU student as well. If you don't mind, may I know if your PFDA assignment's question is the same as mine?

**Comment by Nawin151** [comment]
Yes, our PFDA Assignment is same 😅. And your questions are awesome 😎. Our
module leader gave nice complement on your questions ❣️

**Comment by Ricky0625** [comment]
Ahhh I see haha. Glad to hear that 😆

I wish you all the best on your assignment!

**Comment by Nawin151** [comment]
Looks great, thank you!

**Comment by Nawin151** [comment]
Thank you sir 😁

**Pull request merged**
